PROGRAM MAIN_ICE_ADJUST

USE XRD_GETOPTIONS,  ONLY: INITOPTIONS, GETOPTION, CHECKOPTIONS
USE WRITEDATA_ICE_ADJUST_MOD, ONLY: WRITEDATA_ICE_ADJUST
USE MODD_IO,         ONLY: TFILEDATA
! USE STACK_MOD

IMPLICIT NONE

INTEGER      :: KLEV
INTEGER      :: KRR

INTEGER :: NPROMA, NGPBLKS, NFLEVG
INTEGER :: IBL, JLON, JLEV

TYPE(TFILEDATA)          :: TPFILE
LOGICAL                  :: LLCHECK
LOGICAL                  :: LLCHECKDIFF
LOGICAL                  :: LLDIFF
INTEGER                  :: IBLOCK1, IBLOCK2
INTEGER                  :: ISTSZ, JBLK1, JBLK2
INTEGER                  :: NTID, ITID


REAL(KIND=8) :: TS,TE
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD
INTEGER :: ITIME, NTIME
INTEGER :: IRANK, ISIZE
LOGICAL :: LLVERBOSE, LLSTAT, LLBIND

CALL INITOPTIONS ()
NGPBLKS = 1
CALL GETOPTION ("--blocks", NGPBLKS)
NPROMA = 50
CALL GETOPTION ("--nproma", NPROMA)
NFLEVG = 15
CALL GETOPTION ("--nflevg", NFLEVG)
CALL GETOPTION ("--check",  LLCHECK)
CALL GETOPTION ("--checkdiff",  LLCHECKDIFF)
IBLOCK1 = 1
CALL GETOPTION ("--check-block-1", IBLOCK1)
IBLOCK2 = NGPBLKS
CALL GETOPTION ("--check-block-2", IBLOCK2)
CALL GETOPTION ("--stat", LLSTAT)
NTIME = 1
CALL GETOPTION ("--times", NTIME)
CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--bind", LLBIND)
CALL CHECKOPTIONS ()

LLDIFF = .FALSE.

IRANK = 0
ISIZE = 1


CALL WRITEDATA_ICE_ADJUST (NPROMA, NGPBLKS, NFLEVG,  LLVERBOSE)


END PROGRAM
