PROGRAM MAIN_ICE_ADJUST

USE XRD_GETOPTIONS,  ONLY: INITOPTIONS, GETOPTION, CHECKOPTIONS
USE GETDATA_ICE_ADJUST_MOD, ONLY: GETDATA_ICE_ADJUST
USE WRITEDATA_ICE_ADJUST_MOD, ONLY: WRITEDATA_ICE_ADJUST
! USE COMPUTE_DIFF,    ONLY: DIFF
! USE MODI_ICE_ADJUST
! USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t
USE MODD_IO,         ONLY: TFILEDATA
! USE MODD_PHYEX,      ONLY: PHYEX_t
USE STACK_MOD
USE OMP_LIB
! USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

INTEGER      :: KLEV
INTEGER      :: KRR

REAL,    ALLOCATABLE   :: PRHODJ         (:,:,:)
REAL,    ALLOCATABLE   :: PEXNREF        (:,:,:)
REAL,    ALLOCATABLE   :: PRHODREF       (:,:,:)
REAL,    ALLOCATABLE   :: PPABSM         (:,:,:)
REAL,    ALLOCATABLE   :: PTHT           (:,:,:)
REAL,    ALLOCATABLE   :: PSIGS          (:,:,:)
REAL,    ALLOCATABLE   :: PMFCONV        (:,:,:)
REAL,    ALLOCATABLE   :: PRC_MF         (:,:,:)
REAL,    ALLOCATABLE   :: PRI_MF         (:,:,:)
REAL,    ALLOCATABLE   :: PCF_MF         (:,:,:)
REAL,    ALLOCATABLE   :: PTHS           (:,:,:)
REAL,    ALLOCATABLE   :: PRS            (:,:,:,:)
REAL,    ALLOCATABLE   :: PSRCS          (:,:,:)
REAL,    ALLOCATABLE   :: PCLDFR         (:,:,:)
REAL,    ALLOCATABLE   :: PHLC_HRC       (:,:,:)
REAL,    ALLOCATABLE   :: PHLC_HCF       (:,:,:)
REAL,    ALLOCATABLE   :: PHLI_HRI       (:,:,:)
REAL,    ALLOCATABLE   :: PHLI_HCF       (:,:,:)
REAL,    ALLOCATABLE   :: ZRS            (:,:,:,:)
REAL,    ALLOCATABLE   :: ZZZ            (:,:,:)
REAL,    ALLOCATABLE   :: ZSIGQSAT       (:,:)
REAL,    ALLOCATABLE   :: ZICE_CLD_WGT   (:,:)
REAL,    ALLOCATABLE   :: ZDUM1          (:,:,:)
REAL,    ALLOCATABLE   :: ZDUM2          (:,:,:)
REAL,    ALLOCATABLE   :: ZDUM3          (:,:,:)
REAL,    ALLOCATABLE   :: ZDUM4          (:,:,:)
REAL,    ALLOCATABLE   :: ZDUM5          (:,:,:)

REAL,    ALLOCATABLE   :: PRS_OUT        (:,:,:,:)
REAL,    ALLOCATABLE   :: PSRCS_OUT      (:,:,:)
REAL,    ALLOCATABLE   :: PCLDFR_OUT     (:,:,:)
REAL,    ALLOCATABLE   :: PHLC_HRC_OUT   (:,:,:)
REAL,    ALLOCATABLE   :: PHLC_HCF_OUT   (:,:,:)
REAL,    ALLOCATABLE   :: PHLI_HRI_OUT   (:,:,:)
REAL,    ALLOCATABLE   :: PHLI_HCF_OUT   (:,:,:)

INTEGER :: NPROMA, NGPBLKS, NFLEVG
INTEGER :: IBL, JLON, JLEV

! TYPE(DIMPHYEX_t)         :: D, D0
! TYPE(PHYEX_t)            :: PHYEX
TYPE(TFILEDATA)          :: TPFILE
LOGICAL                  :: LLCHECK
LOGICAL                  :: LLCHECKDIFF
LOGICAL                  :: LLDIFF
INTEGER                  :: IBLOCK1, IBLOCK2
INTEGER                  :: ISTSZ, JBLK1, JBLK2
INTEGER                  :: NTID, ITID

REAL, ALLOCATABLE :: PSTACK(:,:)
TYPE (STACK) :: YLSTACK

REAL(KIND=8) :: TS,TE
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD
INTEGER :: ITIME, NTIME
INTEGER :: IRANK, ISIZE
LOGICAL :: LLVERBOSE, LLSTAT, LLBIND
! REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

CALL INITOPTIONS ()
NGPBLKS = 296
CALL GETOPTION ("--blocks", NGPBLKS)
NPROMA = 32
CALL GETOPTION ("--nproma", NPROMA)
NFLEVG = -1
CALL GETOPTION ("--nflevg", NFLEVG)
CALL GETOPTION ("--check",  LLCHECK)
CALL GETOPTION ("--checkdiff",  LLCHECKDIFF)
IBLOCK1 = 1
CALL GETOPTION ("--check-block-1", IBLOCK1)
IBLOCK2 = NGPBLKS
CALL GETOPTION ("--check-block-2", IBLOCK2)
CALL GETOPTION ("--stat", LLSTAT)
NTIME = 1
CALL GETOPTION ("--times", NTIME)
CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--bind", LLBIND)
CALL CHECKOPTIONS ()

LLDIFF = .FALSE.

IRANK = 0
ISIZE = 1
IF (LLBIND) THEN
  CALL LINUX_BIND      (IRANK, ISIZE)
  CALL LINUX_BIND_DUMP (IRANK, ISIZE)
ENDIF

CALL GETDATA_ICE_ADJUST (NPROMA, NGPBLKS, NFLEVG, PRHODJ, PEXNREF, PRHODREF, PPABSM, PTHT, ZICE_CLD_WGT,     &
& ZSIGQSAT, PSIGS, PMFCONV, PRC_MF, PRI_MF, PCF_MF, ZDUM1, ZDUM2, ZDUM3, ZDUM4, ZDUM5, &
& PTHS, PRS, PSRCS, PCLDFR, PHLC_HRC, PHLC_HCF, &
& PHLI_HRI, PHLI_HCF, ZRS, ZZZ, PRS_OUT, PSRCS_OUT, PCLDFR_OUT, PHLC_HRC_OUT, PHLC_HCF_OUT,       &
& PHLI_HRI_OUT, PHLI_HCF_OUT, LLVERBOSE)

CALL WRITEDATA_ICE_ADJUST (NPROMA, NGPBLKS, NFLEVG, PRHODJ, PEXNREF, PRHODREF, PPABSM, PTHT, ZICE_CLD_WGT,     &
& ZSIGQSAT, PSIGS, PMFCONV, PRC_MF, PRI_MF, PCF_MF, ZDUM1, ZDUM2, ZDUM3, ZDUM4, ZDUM5, &
& PTHS, PRS, PSRCS, PCLDFR, PHLC_HRC, PHLC_HCF, &
& PHLI_HRI, PHLI_HCF, ZRS, ZZZ, PRS_OUT, PSRCS_OUT, PCLDFR_OUT, PHLC_HRC_OUT, PHLC_HCF_OUT,       &
& PHLI_HRI_OUT, PHLI_HCF_OUT, LLVERBOSE)

KLEV = SIZE (PRS, 2)
KRR  = SIZE (PRS, 3)

IF (LLVERBOSE) PRINT *, " KLEV = ", KLEV, " KRR = ", KRR

PRINT *, " NPROMA = ", NPROMA, " KLEV = ", KLEV, " NGPBLKS = ", NGPBLKS


END PROGRAM
