# -*- coding: utf-8 -*-
from ifs_physics_common.framework.stencil import compile_stencil
from ice3_gt4py.drivers.config import default_python_config
from ifs_physics_common.framework.config import GT4PyConfig
import sys
import logging
import itertools

from ice3_gt4py.phyex_common.phyex import Phyex

logging.basicConfig(stream=sys.stdout, level=logging.INFO)


if __name__ == "__main__":
    backends = ["numpy", "gt:cpu_ifirst", "gt:gpu", "cuda", "dace:cpu", "dace:gpu"]
    stencil_collections = [
        "aro_filter",
        "ice_adjust",
        "ice4_nucleation",
        "ice4_fast_rg",
        "ice4_fast_rs",
        "ice4_fast_ri",
        "ice4_nucleation",
        "ice4_rimltc",
        "ice4_rrhong",
        "ice4_slow",
        "ice4_warm",
    ]

    stencil_collections_with_externals = {
        "ice4_nucleation": [
            "tt",
            "v_rtmin",
            "alpi",
            "betai",
            "gami",
            "alpw",
            "betaw",
            "gamw",
            "epsilo",
            "nu20",
            "alpha2",
            "beta2",
            "nu10",
            "beta1",
            "alpha1",
            "mnu0",
            "lfeedbackt",
        ],
        "ice4_fast_rg": [
            "Ci",
            "Cl",
            "tt",
            "lvtt",
            "i_rtmin",
            "r_rtmin",
            "g_rtmin",
            "s_rtmin",
            "icfrr",
            "rcfri",
            "exicfrr",
            "exrcfri",
            "cexvt",
            "crflimit",
            "cxg",
            "dg",
            "fcdryg",
            "fidryg",
            "colexig",
            "colig",
            "ldsoft",
            "estt",
            "Rv",
            "cpv",
            "lmtt",
            "o0depg",
            "o1depg",
            "ex0depg",
            "ex1depg",
            "levlimit",
            "alpi",
            "betai",
            "gami",
            "lwetgpost",
            "lnullwetg",
            "epsilo",
            "frdryg",
            "lbdryg1",
            "lbdryg2",
            "lbsdryg3",
        ],
        "ice4_fast_rs": [
            "s_rtmin",
            "c_rtmin",
            "epsilo",
            "levlimit",
            "alpi",
            "betai",
            "gami",
            "tt",
            "cpv",
            "lvtt",
            "estt",
            "Rv",
            "o0deps",
            "o1deps",
            "ex0deps",
            "ex1deps",
            "lmtt",
            "Cl",
            "Ci",
            "tt",
            "crimss",
            "excrimss",
            "cexvt",
            "crimsg",
            "excrimsg",
            "srimcg",
            "exsrimcg",
            "srimcg3",
            "srimcg2",
            "exsrimcg2",
            "fracss",
            "cxs",
            "lbraccs1",
            "lbraccs2",
            "lbraccs3",
            "lbsaccr1",
            "lbsaccr2",
            "lbsaccr3",
            "bs",
            "fsaccrg",
        ],
        "ice4_fast_ri": [
            "c_rtmin",
            "i_rtmin",
            "lbi",
            "lbexi",
            "o0depi",
            "o2depi",
            "di",
        ],
        "ice4_rimltc": ["tt", "lfeedbackt"],
        "ice4_rrhong": ["r_rtmin", "tt", "lfeedbackt"],
        "ice4_slow": [
            "tt",
            "c_rtmin",
            "v_rtmin",
            "s_rtmin",
            "i_rtmin",
            "g_rtmin",
            "hon",
            "alpha3",
            "beta3",
            "o0deps",
            "ex0deps",
            "ex1deps",
            "o1deps",
            "fiaggs",
            "colexis",
            "exiaggs",
            "cexvt",
            "xcriauti",
            "acriauti",
            "bcriauti",
            "timauti",
            "texauti",
            "o0depg",
            "ex0depg",
            "o1depg",
            "ex1depg",
        ],
        "ice4_warm": [
            "subg_rc_rr_accr",
            "subg_rr_evap_",
            "c_rtmin",
            "r_rtmin",
            "timautc",
            "criautc",
            "cexvt",
            "fcaccr",
            "excaccr",
            "alpw",
            "betaw",
            "gamw",
            "Rv",
            "Cl",
            "lvtt",
            "tt",
            "cpv",
            "o0evar",
            "ex0evar",
            "o1evar",
            "ex1evar",
            "cpd",
            "epsilo",
        ],
    }

    for backend, stencil_collection in itertools.product(backends, stencil_collections):
        gt4py_config = GT4PyConfig(
            backend=backend, rebuild=True, validate_args=True, verbose=True
        )

        logging.info(f"Compile {stencil_collection} stencil_collection on {backend}")

        externals = {
            "lvtt": 0,
            "lstt": 0,
            "tt": 0,
            "subg_mf_pdf": 0,
            "subg_cond": 0,
            "cpd": 0,
            "cpv": 0,
            "Cl": 0,
            "Ci": 0,
            "tt": 0,
            "alpw": 0,
            "betaw": 0,
            "gamw": 0,
            "alpi": 0,
            "betai": 0,
            "gami": 0,
            "Rd": 0,
            "Rv": 0,
            "frac_ice_adjust": 0,
            "tmaxmix": 0,
            "tminmix": 0,
            "criautc": 0,
            "tstep": 0,
            "criauti": 0,
            "acriauti": 0,
            "bcriauti": 0,
            "nrr": 6,
        }

        try:
            stencil = compile_stencil(stencil_collection, gt4py_config, externals)

            logging.info(f"Compilation succeeded for {stencil_collection} on {backend}")

        except:
            logging.error(f"Compilation failed for {stencil_collection} on {backend}")
