MODULE GETDATA_ICE_ADJUST_MOD

USE OMP_LIB
USE ARRAYS_MANIP, ONLY: SETUP, REPLICATE, NPROMIZE, INTERPOLATE, SET
USE PARKIND1, ONLY: JPRD

CONTAINS

SUBROUTINE GETDATA_ICE_ADJUST (NPROMA, NGPBLKS, NFLEVG, LDVERBOSE)

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON
INTEGER      :: KIDIA
INTEGER      :: KFDIA
INTEGER      :: KLEV
INTEGER      :: KRR
INTEGER      :: KDUM

LOGICAL, INTENT(IN) :: LDVERBOSE


REAL(KIND=JPRD), ALLOCATABLE   :: PRHODJ         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PEXNREF        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRHODREF       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PPABSM         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHT           (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSIGS          (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PMFCONV        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRC_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRI_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCF_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHS           (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS            (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS_OUT        (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSRCS_OUT      (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCLDFR_OUT     (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLC_HRC_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLC_HCF_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLI_HRI_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLI_HCF_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZRS            (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZZZ            (:,:,:)

INTEGER, INTENT(IN) :: NPROMA, NGPBLKS
INTEGER :: NGPTOT
INTEGER, INTENT(INOUT) :: NFLEVG
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE

CALL SETUP()

KRR=6
NGPTOT = NPROMA * NGPBLKS

IBL = 1
WRITE (CLFILE, '("data/",I8.8,".dat")') IBL
OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED')
READ (IFILE) KLON, KDUM, KLEV
CLOSE (IFILE)

IF (NFLEVG < 0) NFLEVG = KLEV

IOFF = 0
IBL = 0
LLEXIST = .TRUE.

DO WHILE(LLEXIST)
  IBL = IBL + 1
  WRITE (CLFILE, '("data/",I8.8,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  IF (LDVERBOSE) PRINT *, TRIM (CLFILE)

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

  READ (IFILE) KLON, KDUM, KLEV

  IF (IBL == 1) THEN
    ALLOCATE (PRHODJ       (NGPTOT,KLEV,1))
    ALLOCATE (PEXNREF      (NGPTOT,KLEV,1))
    ALLOCATE (PRHODREF     (NGPTOT,KLEV,1))
    ALLOCATE (PPABSM       (NGPTOT,KLEV,1))
    ALLOCATE (PTHT         (NGPTOT,KLEV,1))
    ALLOCATE (PSIGS        (NGPTOT,KLEV,1))
    ALLOCATE (PMFCONV      (NGPTOT,KLEV,1))
    ALLOCATE (PRC_MF       (NGPTOT,KLEV,1))
    ALLOCATE (PRI_MF       (NGPTOT,KLEV,1))
    ALLOCATE (PCF_MF       (NGPTOT,KLEV,1))
    ALLOCATE (PTHS         (NGPTOT,KLEV,1))
    ALLOCATE (PRS          (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PRS_OUT      (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSRCS_OUT    (NGPTOT,KLEV,1))
    ALLOCATE (PCLDFR_OUT   (NGPTOT,KLEV,1))
    ALLOCATE (ZRS          (NGPTOT,KLEV,0:KRR,1))
    ALLOCATE (ZZZ          (NGPTOT,KLEV,1))
    ALLOCATE (PHLC_HRC_OUT (NGPTOT,KLEV,1))
    ALLOCATE (PHLC_HCF_OUT (NGPTOT,KLEV,1))
    ALLOCATE (PHLI_HRI_OUT (NGPTOT,KLEV,1))
    ALLOCATE (PHLI_HCF_OUT (NGPTOT,KLEV,1))
  ENDIF

  IF (IOFF+KLON > NGPTOT) THEN
    EXIT
  ENDIF

  READ (IFILE) PRHODJ       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PEXNREF      (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRHODREF     (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PSIGS        (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PMFCONV      (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PPABSM       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) ZZZ          (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PCF_MF       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRC_MF       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRI_MF       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) ZRS          (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PRS          (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PTHS         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRS_OUT      (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSRCS_OUT    (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PCLDFR_OUT   (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PHLC_HRC_OUT (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PHLC_HCF_OUT (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PHLI_HRI_OUT (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PHLI_HCF_OUT (IOFF+1:IOFF+KLON,:,1)

  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

END SUBROUTINE

END  MODULE
