! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_MODE_ICE4_RRHONG
  IMPLICIT NONE


CONTAINS



  SUBROUTINE C_ICE4_RRHONG(XTT, XRTMIN, LFEEDBACKT, KPROMA, KSIZE, LDCOMPUTE_DIM_1, LDCOMPUTE, PEXN_DIM_1, PEXN, PLVFACT_DIM_1, PLV&
&FACT, PLSFACT_DIM_1, PLSFACT, PT_DIM_1, PT, PRRT_DIM_1, PRRT, PTHT_DIM_1, PTHT, PRRHONG_MR_DIM_1, PRRHONG_MR) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE MODE_ICE4_RRHONG, ONLY: ICE4_RRHONG
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: XTT
    REAL, INTENT(INOUT) :: XRTMIN
    LOGICAL, INTENT(INOUT) :: LFEEDBACKT
    INTEGER, INTENT(IN) :: KPROMA
    INTEGER, INTENT(IN) :: KSIZE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: LDCOMPUTE_DIM_1
    LOGICAL, INTENT(IN), DIMENSION(LDCOMPUTE_DIM_1) :: LDCOMPUTE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PEXN_DIM_1
    REAL, INTENT(IN), DIMENSION(PEXN_DIM_1) :: PEXN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PLVFACT_DIM_1
    REAL, INTENT(IN), DIMENSION(PLVFACT_DIM_1) :: PLVFACT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PLSFACT_DIM_1
    REAL, INTENT(IN), DIMENSION(PLSFACT_DIM_1) :: PLSFACT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PT_DIM_1
    REAL, INTENT(IN), DIMENSION(PT_DIM_1) :: PT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PRRT_DIM_1
    REAL, INTENT(IN), DIMENSION(PRRT_DIM_1) :: PRRT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PTHT_DIM_1
    REAL, INTENT(IN), DIMENSION(PTHT_DIM_1) :: PTHT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PRRHONG_MR_DIM_1
    REAL, INTENT(OUT), DIMENSION(PRRHONG_MR_DIM_1) :: PRRHONG_MR

    CALL ICE4_RRHONG(XTT, XRTMIN, LFEEDBACKT, KPROMA, KSIZE, LDCOMPUTE, PEXN, PLVFACT, PLSFACT, PT, PRRT, PTHT, PRRHONG_MR)
  END SUBROUTINE C_ICE4_RRHONG

END MODULE C_MODE_ICE4_RRHONG
